### Signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "userName": "hawmidak",
  "email": "hawmidak@gmail.com",
  "password": "hamid1568"
}



### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "userName": "hawmidak@gmail.com",
  "password": "Hamid1568",
  "rememberMe": true
}


### 
POST http://localhost:3000/reset/request-reset-password
Content-Type: application/json

{
  "email": "hawmidak@gmail.com"
}
###
POST http://localhost:3000/reset/validate-reset-token
Content-Type: application/json

{
    "token": "7e001f46-d6c8-44c5-ba6d-a7e37a5fc6b0"
}


### 
POST http://localhost:3000/reset/reset-password
Content-Type: application/json

{
  "token": "7e001f46-d6c8-44c5-ba6d-a7e37a5fc6b0",
  "newPassword": "Hamid1568"
}

