export const sampleUsers = [
  {
    userName: 'test101',
    normalizedUserName: 'TEST101',
    email: 'test101@example.com',
    normalizedEmail: 'TEST101@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$CqJggN.bhoOUD5A1MZpxVu.avrvNOJHTmmVN8SjE12hcFwCg89S12',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test102',
    normalizedUserName: 'TEST102',
    email: 'test102@example.com',
    normalizedEmail: 'TEST102@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$L8myhPtl1fmW3XqsYYlkGuBQTu8seA7p.NrTWzDFa.TOo7OG6VPba',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test103',
    normalizedUserName: 'TEST103',
    email: 'test103@example.com',
    normalizedEmail: 'TEST103@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$l6jNE8U4LaeI2rMbAlD3SuUg783mPIomstKJ6Lf3Nupiu2VVXAyRm',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test104',
    normalizedUserName: 'TEST104',
    email: 'test104@example.com',
    normalizedEmail: 'TEST104@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$ECfvG1eOl5Hw4m6j4Buyp.gXK0QPk0erb.EXrf5/wPVrUOwoKeKTe',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test105',
    normalizedUserName: 'TEST105',
    email: 'test105@example.com',
    normalizedEmail: 'TEST105@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$IFGOhERSA3wK5wiTMi2KNek.VryVfYNBzHoBndhAAGpZ9Mx14gq5y',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test106',
    normalizedUserName: 'TEST106',
    email: 'test106@example.com',
    normalizedEmail: 'TEST106@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$5.bisoXBTQvnyDi.smzU3eW.04Ejj5ErD6s.omJKsRZYgw3MWnClK',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test107',
    normalizedUserName: 'TEST107',
    email: 'test107@example.com',
    normalizedEmail: 'TEST107@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$gAfaGpZPmK7oa5QCwragUuvrAAkiRzsdFnGFzitneGzNNIwxu1vVu',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test108',
    normalizedUserName: 'TEST108',
    email: 'test108@example.com',
    normalizedEmail: 'TEST108@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$3jLKllpAGeRAnLFbDCcG6e7pcQWDxUyQXlwKSjwue.O04EIx.0ozi',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test109',
    normalizedUserName: 'TEST109',
    email: 'test109@example.com',
    normalizedEmail: 'TEST109@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$6SJ9OF6NB1V1YPx331E9.ezA/IQ1ZbyRDozV.48BCwYZyWoZ4/bLS',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test110',
    normalizedUserName: 'TEST110',
    email: 'test110@example.com',
    normalizedEmail: 'TEST110@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$o8pVnoModtUKKsIvZSEOGe/qgRGRzagGzNj0WhjuJiSKkkTyrkIi2',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test111',
    normalizedUserName: 'TEST111',
    email: 'test111@example.com',
    normalizedEmail: 'TEST111@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$nzn0wLSP/BYxePfr7h3c.efteVqwLoc8JTUBpWimC3pZ.2ZHVeSam',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test112',
    normalizedUserName: 'TEST112',
    email: 'test112@example.com',
    normalizedEmail: 'TEST112@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$L762H02H/ugzCfy2xXLCY.O1970IYKYiciliP6zdd7u7U9jYD0oFu',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test113',
    normalizedUserName: 'TEST113',
    email: 'test113@example.com',
    normalizedEmail: 'TEST113@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$aP2Eafj1VRmWdAFXiMvMD.8PlTWx84Ey5uxyyBy5icrBXu/LCg416',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test114',
    normalizedUserName: 'TEST114',
    email: 'test114@example.com',
    normalizedEmail: 'TEST114@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$m7Yxz2UWFCXX7zWh04nDpeeDEJR5CBkc/LhD/xmKIXYonfHzbM7EG',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test115',
    normalizedUserName: 'TEST115',
    email: 'test115@example.com',
    normalizedEmail: 'TEST115@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$cDoN.B6DtYf9hkMVo5t13.3a8qEKa4P0No9Krv0u5g3XApZZSJlQu',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test116',
    normalizedUserName: 'TEST116',
    email: 'test116@example.com',
    normalizedEmail: 'TEST116@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$EMX5WQj2oqrumyAN7GafhOvwk48I/MCn4.nQj9b2HNxmDqh12akhC',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test117',
    normalizedUserName: 'TEST117',
    email: 'test117@example.com',
    normalizedEmail: 'TEST117@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$omNE4NUn6NaG9.XL5Mztve/X2IZmhHZLk/.WN0WpxE1Rk8gDTcr0G',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test118',
    normalizedUserName: 'TEST118',
    email: 'test118@example.com',
    normalizedEmail: 'TEST118@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$8A4FfBmDU4VuBvppBQOm9edpY2uf7j0KXcWE2y5gx5zkTgjWHzctW',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test119',
    normalizedUserName: 'TEST119',
    email: 'test119@example.com',
    normalizedEmail: 'TEST119@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$4rCVWr.CufAbzhkgJ3zGOOWs86PFz2MAOhaDgCOAMdxzEA6TesQZi',
    isPrivate: false,
    bio: '',
    followerCount: 0
  },
  {
    userName: 'test120',
    normalizedUserName: 'TEST120',
    email: 'test120@example.com',
    normalizedEmail: 'TEST120@EXAMPLE.COM',
    firstName: '',
    lastName: '',
    profileImage: '',
    passwordHash: '$2b$10$hYjomJ4kfhGeTmPBnp9DHOsPauy6XzDyZxFZW0jueNiCAXVmlDqR2',
    isPrivate: false,
    bio: '',
    followerCount: 0
  }
]