export enum ErrorCode {
    // Missing field:
    MISSING_FOLLOWING_USERNAME,
    MISSING_FOLLOWER_USERNAME,
    MISSING_COMMENTID,
    MISSING_POSTID,

    // Invalid field value:
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_FOLLOWING_USERNAME,
    INVALID_POST_ID,
    INVALID_ACCEPTED_ARGUMENT,
    COMMENT_INVALID_PARENT_ID,

    // Logic validation errors:
    EMAIL_EXISTS,
    USERNAME_EXISTS,
    INVALID_OR_EXPIRED_TOKEN,
    MISSING_PHOTO_FOR_POST,
    PHOTO_COUNT_EXCEDED,
    NO_SUCH_REQUEST,
    ALREADY_ACCEPTED,
    INVALID_FOLLOW_REQUEST,

    // File errors:
    FILE_TOO_LARGE,
    FILE_UPLOAD_ERROR,

    // Authorization/authentication errors:
    UNAUTHORIZED,
    INVALID_USERNAME_OR_PASSWORD,
    SWITCH_ACCOUNT_ERROR,

    // forbidden errors:
    USER_IS_NOT_FOLLOWED,
    YOU_ARE_BLOCKED,
    EDIT_POST_ACCESS_DENIED,
    CREATOR_IS_BLOCKED_BY_YOU,
    USER_IS_PRIVATE,

    // Not found errors:
    COMMENT_NOT_FOUND,
    PAGE_NOT_FOUND,
    POST_NOT_FOUND,
    USER_NOT_FOUND,

    // Unknown error:
    UNKNOWN_ERROR,

    // New errors:
    TOO_MANY_ACCOUNTS,
}
