### Signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "userName": "hawmidak",
  "email": "hawmidak@gmail.com",
  "password": "hamid1568"
}



### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "userName": "hawmidak",
  "password": "Hamid1568",
  "rememberMe": true
}


### 
POST http://localhost:3000/reset/request-reset-password
Content-Type: application/json

{
  "email": "hawmidak@gmail.com"
}
###
POST http://5.34.193.118:3000/api/reset/validate-reset-token
Content-Type: application/json

{
    "token": "254ea4c5-566a-472e-8d37-7fe703de16b4"
}


### 
POST http://localhost:3000/api/reset/reset-password
Content-Type: application/json

{
  "token": "0e2a30ec-73da-4638-9e6b-95822e036580",
  "newPassword": "Hamid1568"
}

###
POST http://localhost:3000/api/api-docs
