### Signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "userName": "hawmidak",
  "email": "hawmidak@gmail.com",
  "password": "hamid1568"
}



### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "userName": "hawmidak",
  "password": "Hamid1568",
  "rememberMe": true
}


### 
POST http://5.34.193.118:3000/api/reset/request-reset-password
Content-Type: application/json

{
  "email": "hawmidak@gmail.com"
}

###
POST http://5.34.193.118:3000/api/reset/validate-reset-token
Content-Type: application/json

{
    "token": "c4bb8b85-66d4-44a7-82a7-d2d581c317c9"
}


### 
POST http://localhost:3000/api/reset/reset-password
Content-Type: application/json

{
  "token": "a3d53231-8a2d-4933-8c52-48ba960fa933",
  "newPassword": "Hamid1568"
}

###
POST http://localhost:3000/api/users/followingers
Content-Type: application/json

{
    "userName": "hawmidak",
    "isFollowing": false,
    "page": 1,
    "limit": 10
}

###
POST http://5.34.193.118:3000/api/users/followingers
Content-Type: application/json

{
    "userName": "21eich",
    "isFollowing": true,
    "page": 1,
    "limit": 10
}



###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "userName": "hawmidak",
  "password": "Hamid1568",
  "rememberMe": true
}


###
POST http://localhost:3000/api/users/follow
Content-Type: application/json

{
"followingUserName" : "amir70"
}