### Signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "userName": "hawmidak",
  "email": "hawmidak@gmail.com",
  "password": "hamid1568"
}



### Login
POST http://5.34.193.118:3000/users/login
Content-Type: application/json

{
  "userName": "hawmidak@gmail.com",
  "password": "Hamid553306",
  "rememberMe": true
}


### 
POST http://localhost:3000/reset/request-reset-password
Content-Type: application/json

{
  "email": "hawmidak@gmail.com"
}
###
POST http://localhost:3000/reset/validate-reset-token
Content-Type: application/json

{
    "token": "44f98ec2-1d9a-4ff5-89ab-dd19b50cbdcc"
}


### 
POST http://localhost:3000/reset/reset-password
Content-Type: application/json

{
  "token": "44f98ec2-1d9a-4ff5-89ab-dd19b50cbdcc",
  "newPassword": "Hamid553306"
}

