name: Gramverse Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run commands
        run: |
          cd ~/gramverse/gramverse-backend
          git pull
          cd ~/gramverse
          sudo docker-compose build

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run commands
        run: |
          cd ~/gramverse
          sudo docker-compose up --d
